version: "3.8"
services:
    mysql:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ideasoft-facturacion
            MYSQL_USER: ideasoft
            MYSQL_PASSWORD: while(vida==false)
        ports:
            - "3307:3306"
